language: node_js
node_js:
  - "8.6.0"
script: ./travis-build.sh $TRAVIS_BRANCH
deploy:
  - provider: s3
    access_key_id: "$ACCESS_KEY_ID"
    secret_access_key: "$ACCESS_KEY_SECRET"
    bucket: stage-ed-era-com
    region: eu-west-1
    detect_encoding: true
    local_dir: build
    skip_cleanup: true
    acl: public_read
    cache_control: "max-age=60"
    on: preproduction

  - provider: s3
    access_key_id: "$ACCESS_KEY_ID"
    secret_access_key: "$ACCESS_KEY_SECRET"
    bucket: www-ed-era-com
    region: eu-west-1
    detect_encoding: true
    local_dir: build
    skip_cleanup: true
    acl: public_read
    cache_control: "max-age=60"
    on: master
