let ua = {
  home: 'Головна',
  aboutUs: 'Про нас',
  benefits: 'Переваги',
  ourProducts: 'Наші продукти',
  Processes: 'Процес',
  Partners: 'Партнери',
  Question: 'Питання',
  Contacts: 'Контакти',
  mainTitle: 'Студія онлайн&#x2060;-освіти ЕдЕра',
  mainTitleDescript: 'Ми створюємо онлайн&#x2060;-курси та&nbsp;інтерактивні продукти. <br>Захопливі, гарні, ефективні.',
  buttonText: 'Замовити курс',
  ProductsGeneral: 'Продукти для&nbsp;широкого загалу',
  ProductsBusiness: 'Продукти для&nbsp;бізнесу',
  LearnMore: 'детальніше',
  Mission: 'Наша місія&nbsp;— надихати освітою.<br> Для цього ми більше 7&nbsp;років створюємо онлайн-курси, навчальні платформи, інтерактивні ігри та підручники. Наші курсипроходить кожен четвертий вчитель в&nbsp;Україні та&nbsp;співробітники найбільших корпоративних мереж. Ми перші в&nbsp;Україні почали масово підвищувати кваліфікацію онлайн.',
  WeCreate: 'Ми можемо втілити онлайн-курс будь-якої складності, інтерактивну гру, як&nbsp;для&nbsp;НАБУ або цілу платформу, як&nbsp;для&nbsp;ЦВК. Або освітній серіал, як&nbsp;для&nbsp;Мінцифри. Можемо створити онбординг для ваших співробітників, як&nbsp;для&nbsp;Смартес або розробити навчальну екосистему з&nbsp;нуля&nbsp;— як&nbsp;для&nbsp;Бекстейджу.',
  WeOffer: 'У нас є&nbsp;власний R&D&nbsp;юніт, продакшн повного циклу, та&nbsp;натхненна команда у&nbsp;Києві. А&nbsp;в&nbsp;Берліні&nbsp;— технологічний стартап та&nbsp;унікальна LMS.',
  projects: 'проектів',
  users: 'користувачів на платформі',
  experience: 'років досвіду',
  team: 'членів команди',
  Methodological: 'Методологічна<br>експертиза',
  EachEdEraProduct: 'Кожен продукт EdEra&nbsp;— результат роботи R&D юніта: експертів з&nbsp;когнітивістики та&nbsp;освітнього дизайну. Повноцінне дослідження і&nbsp;аналіз&nbsp;— обов’язкова частина нашої роботи. Завдяки ним ми знаємо, яких цілей має досягти продукт і&nbsp;як це&nbsp;зробити.',
  Individual: 'Індивідуальний підхід&nbsp;— кастомна розробка',
  OwnProduction: 'Індивідуальна розробка, власний продакшн, R&D та&nbsp;технічна команда роблять нас гнучкими для роботи із будь-якими задачами. Власний продакшн, R&D та&nbsp;технічна команда дозволяють працювати із&nbsp;будь-якими завданнями. Ми можемо розробити інтерактивні курси або квести на&nbsp;всіх LMS з&nbsp;використанням будь-яких навчальних технологій.',
  Process: 'Технологічна розробка і&nbsp;власна&nbsp;LMS',
  HaveOwnPlatform: 'Ми маємо власну платформу для&nbsp;розміщення курсів. Це дозволяє нам підібрати оптимальний формат під&nbsp;кожний проєкт, аналізувати статистику та&nbsp;швидко додавати унікальні фічі.',
  OurProducts: 'Продукти',
  generalPublic: 'Для широкого загалу',
  ForBusinesses: 'Для бізнесу',
  Massive: 'Масові освітні<br>онлайн-курси',
  AnyTargetAudience: 'Будь-яка аудиторія та тема, сертифікація, оцінювання.',
  EducationalGames: 'Навчальні ігри',
  ArticulateStoryline: 'Articulate storyline, кастомний код.',
  LearningPlatforms: 'Навчальні платформи',
  DevelopmentPlatform: 'Розробка платформи, алгоритмів та контенту.',
  Cases: 'Приклади кейсів:',
  Onboarding: 'Онбординг та офбординг',
  Content: 'Контент та технічна реалізація.',
  EducationalEcosystem: 'Навчальна екосистема',
  IndividualResearch: 'Індивідуальні дослідження, навчальні алгоритми, контент.',
  OnlineCourses: 'Онлайн-курси',
  AnyTopic: 'Будь-яка тема та формат.',
  Nus: 'Нова українська школа',
  teachTeachers: 'Задача: Навчити вчителів навчатись онлайн. Розробити перший в Україні обов’язковий онлайн-курс для всіх вчителів початкової школи в межах реформи НУШ.',
  DevelopedSimpleInformative: 'Що зробили: Розробили простий та інформативний курс для навчання вчителів. Довели, що онлайн-освіта в Україні можлива у національних масштабах.',
  teachersHaveBeenTaught: 'Результат: Навчили 265 000 вчителів навчатись в онлайн-форматі. З них 168 000 отримали сертифікат про успішне завершення курсу.',
  IREx: 'Айрекс',
  promoteMediaLiteracy: 'Задача: Популяризувати медіаграмотність в Україні та надати українцям інструменти критичного мислення та ефективного аналізу інформації.',
  developedCreativeOnlineCourse: 'Що зробили: Розробили креативний онлайн-курс з анімаційними матеріалами, чатботами та тестами в сучасній айдентиці. Курс доступний для проходження трьом',
  usersIREX: 'Результат: 42 000 користувачів',
  NABu: 'НAБУ',
  developEducationalGame: 'Задача: Розробити освітню гру у форматі кейсів та інтерактивного розслідування для теперішніх та майбутніх детективів НАБУ',
  developedAnEducationalGame: 'Що зробили: Розробили освітню гру з 9 етапів, відеопояснень, кейсових відео допиту, обшуку та судового засідання. Застосували підхід edutainment та кейсове навчання, а розмістили гру в ПО Articulate Storyline.',
  usersInFirstDay: 'Результат: 902 користувачі за першу добу, 12 866 користувачів за пів року.',
  Feedback: 'Відгук:',
  Victoria: 'Вікторія Івашинют',
  VictoriaDescript: 'керівниця Відкритого офісу НАБУ',
  InvestigationIsConducted: '«Слідство веде НАБУ» став першим освітнім онлайн проєктом для НАБУ, а ігровий формат курсу — першим для «ЕдЕри». Втім ми чудово впоралися з цією непростою та цікавою задачею. Креатив, відданість справі та злагоджена командна робота були запорукою нашого спільного успіху. І карантин в країні не зумів поламати наші плани.',
  Prosvita: 'ЦВК: Просвіта',
  creativeConcept: 'Задача: Розробити креативну концепцію та створити імерсивну навчальну платформу про вибори для кожного мешканця України.',
  educationalPlatformWhichOffersLearning: 'Що зробили: Ґейміфіковану освітню платформу, навчання на якій відбувається у форматі спілкування в месенджері, та серію відео, інтегрованих у діалоги.',
  ResultPROSVITA: 'Результат: Проста в навігації освітня платформа в оновленому візуальному стилі ЦВК. Перша в Україні сучасна навчальна платформа на базі державного органа.',
  Vladislav: 'Владислав Єленчи',
  ProductManager: 'продакт-менеджер Ради Європи',
  EdEraFaced: '«Перед ЕдЕрою було амбітне завдання — за 4 місяці кастомізувати свою платформу й випустити 98 відео для 4 курсів. І в них вийшло! А головне — вийшло якісно»',
  Backstage: 'Бекстейдж',
  BackstageTask: 'Задача: Трансформувати офлайн-навчання в онлайн-формат. Зберегти корпоративну екосистему та створити нативний онбординг для нових співробітників мережі.',
  BackstageSolution: 'Що зробили: Повний онбординг нового працівника — від корпоративної культури до точних скриптів та протоколів роботи. Десятки проміжних тестувань та фінальний рейтинговий бал співробітника/-ці.',
  BackstageResult: 'Результат:  Сотні майстрів мережі пройшли онлайн-онбординг та навчання, а директори салонів оцінили навички нових співробітників та ухвалили фінальне рішення щодо долучення їх до команди.',
  Karina: 'Карина Дубініна',
  KarinaDescript: 'засновниця мережі салонів краси Backstage',
  KarinaFeedback: '«До нас весь час приходять нові майстри, тому навчання — це нагальна потреба. Разом із командою EdEra ми знайшли рішення, створивши платформу з онлайн-курсами для майстрів. Тепер онбординг автоматизований. Майстри мають цілодобовий доступ до навчальних матеріалів та можуть проходити автоматизовані тести, а адміністрації легше відстежувати ефективність процесу. Вже три курси для майстрів забезпечують регулярне навчання доступною мовою. Відеоуроки відтворюють весь процес роботи майстра у цікавому форматі. Слухач ніби «присутній» безпосередньо в кабінеті майстра, а сама платформа зручна та гнучка.»',
  Ukrtelecom: 'Укртелеком',
  UkrtelecomTask: 'Задача: Створити два курси для підвищення кваліфікації співробітників «Укртелекому» — з цифрової грамотності та ділової української мови.',
  UkrtelecomSolution: 'Що зробили: Зробили корпоративне навчання динамічним та корисним для сотень працівників із різним рівнем навичок та досвіду.',
  UkrtelecomResult: 'Результат: Розробили 2 екосистеми корпоративних курсів — з відеопоясненнями та кейсовими ситуаціями, додатковими матеріалами та тестуванням. Обидва курси у відкритому доступі для усіх співробітників «Укртелекому».',
  Olesya: 'Олеся Піцик',
  OlesyaDescript: 'менеджерка з розвитку управлінських компетенцій',
  OlesyaFeedback: 'З командою EdEra ми реалізували 2 відео-курси: «Ділова Українська Мова» та «Цифрова Грамотність» «під ключ». <br>Зараз навчальні модулі доступні всім працівникам нашої компанії на корпоративній платформі дистанційного навчання. <br>Саме через широку цільову аудиторію (курси проходять і новачки, і просунуті користувачі та впевнені мовці), нам важливо було знайти партнера, який би зробив навчання цікавим та наповненим універсальною й актуальною інформацією саме для бізнес-середовища. <br>Завдяки злагодженій роботі методологів, авторів та команді продакшену EdEra вийшов якісний продукт, яким ми задоволені.',
  ProductCreation: 'Процес створення продуктів',
  ProductDevelopmentInvolves: 'Створення продукту відбувається впродовж 7&nbsp;кроків: від дослідження&nbsp;— до&nbsp;аналітики даних. Ми&nbsp;можемо розробити комплексний продукт або, наприклад, здійснити лише аналітику ринку та&nbsp;розробити концепцію вашого проєкту.',
  research: 'Дослідження ринку та&nbsp;ЦА',
  teamAnalyzes: 'R&D&nbsp;команда аналізує потреби аудиторії та&nbsp;продукту.',
  EducationalMethodology: 'Розробка навчальної методології та&nbsp;створення контенту&nbsp;R&D.',
  TeamDevelops: 'Команда розроблює освітню концепцію: структуру та&nbsp;оптимальну навчальну методологію продукту і&nbsp;сам контент.',
  CommunicationPromotion: 'Комунікація',
  CreativeCommunication: 'Комунікаційна та&nbsp;креативна команда розробляють та&nbsp;реалізують комунікаційну кампанію продукту: партнерства з&nbsp;медіа, контент для&nbsp;соцмереж, e-mail&nbsp;розсилки тощо.',
  ProjectConcept: 'Формування концепту та&nbsp;айдентики проєкту',
  designEachComponent: 'Креативна команда розробляє концепцію проєкту&nbsp;— меседжі та&nbsp;унікальні прояви. А&nbsp;також&nbsp;— візуальне оформлення кожного складника продукту.',
  Production: 'Продакшн',
  teamEnsures: 'Проєктна команда здійснює контентний та&nbsp;технічний продакшн. Контентний продакшн охоплює розробку відео, аудіо, тестів&nbsp;— від&nbsp;тестового зйомки до&nbsp;фінального постпродакшну. <br>Технічний продакшн&nbsp;— це розробка, дизайн та&nbsp;верстка сайту.',
  ProductLaunch: 'Запуск та&nbsp;підтримка продукту',
  projectTeamLaunches: 'Проєктна команда здійснює публічний запуск продукту, технічний та&nbsp;інформаційний супровід користувачів.',
  DataAnalysis: 'Аналітика даних',
  teamAnalyzesQuantitative: 'R&D&nbsp;команда аналізує кількісні та&nbsp;якісні дані проходження курсу та&nbsp;користувацькі відгуки.',
  question1: 'Маю готовий курс. Чи можна розмістити?',
  answer1: 'На платформі EdEra ми розміщуємо лише ті освітні продукти, які розроблені у партнерстві з нами. Проте, якщо ви маєте готовий курс і шукаєте лише платформу для розміщення, можете звернутися до нашого партнера Workademy.',
  question2: 'Хто матиме доступ до продукту?',
  answer2: 'До курсів для широкого загалу доступ матимуть усі користувачі платформи EdEra. До корпоративних курсів - безпосередньо ваша цільова аудиторія. Такий курс може бути закритим.',
  question3: 'Чи можна використовувати свій дизайн?',
  answer3: 'Так! Якщо ви маєте свій брендинг та гайдлайни до нього, ми адаптуємо дизайн під формат онлайн-продукту та зробимо айдентику на основі вашого брендбуку.',
  question4: 'Чи можете ви лише зняти курс — без промо та розміщення?',
  answer4: 'Так, ми можемо зробити курс «під ключ» та передати усі готові матеріали для розміщення вам.',
  question5: 'Які комунікаційні активності ви робите?',
  answer5: 'Ми розробляємо і втілюємо повноцінні комунікаційні стратегії і кампанії: від просування продукту в соціальних мережах до спецпроєктів та колаборацій з медіа.',
  question6: 'Чи можуть користувачі отримувати сертифікати?',
  answer6: 'Так, генерація сертифікатів передбачена усіма LMS (Learning System Management) платформами на яких ми розміщуємо онлайн-продукти.',
  calculatePrice: 'Ціну кожного проєкту ми&nbsp;розраховуємо індивідуально після детального брифу. Напишіть&nbsp;нам на&nbsp;<a href="partnerships@ed-era.com">partnerships@ed-era.com</a>, і&nbsp;ми відповімо&nbsp;вам на&nbsp;всі запитання.',
  Share: 'Поділитись в соціальних мережах',
  TellUs: 'Розкажіть нам ідею проєкту — а наші менеджери партнерств зв’яжуться з вами.',
  name: 'Ім’я',
  Company: 'Назва компанії',
  Phone: 'Телефон',
  Submit: 'Надіслати заяву',
  WhatProblem: 'Яку задачу ви б хотіли вирішити разом з нами?',
};

let eng = {
  home: 'Home',
  aboutUs: 'About us',
  benefits: 'Why us?',
  ourProducts: 'Our products',
  Processes: 'Processes',
  Partners: 'Partners',
  Question: 'FAQ',
  Contacts: 'Contacts',
  mainTitle: 'Online education studio EdEra',
  mainTitleDescript: 'We create online courses and interactive products.<br>Exciting, beautiful, and effective.',
  buttonText: 'Order a course',
  ProductsGeneral: 'Products for the general public',
  ProductsBusiness: 'Products for business',
  LearnMore: 'Learn more',
  Mission: 'Our mission is to inspire through education. To achieve that, we have been creating online courses, learning platforms, interactive games, and textbooks for more than 7 years. Every fourth teacher in Ukraine and employees of the largest corporate networks take our courses.',
  WeCreate: 'We can create an online course of any complexity. For example, an interactive game as we did for NABU or an entire platform like the one for CEC. It may be an educational series like the one for the Ministry of Digital Transformation. We also can develop onboarding for your employees, as we did for Smartass, or develop a learning ecosystem from scratch, as we did for Backstage.',
  WeOffer: 'We offer our own R&D unit, full-cycle production, and an inspired team in Kyiv. In Berlin, we also develop a technology startup and a unique LMS.',
  projects: 'projects',
  users: 'users on the platform',
  experience: 'years of experience',
  team: 'team members',
  Methodological: 'Methodological expertise',
  EachEdEraProduct: 'Each EdEra product is supported by the work of the R&D unit: experts in cognitive science and educational design. Comprehensive research and analysis is a mandatory part of our work. Thanks to them, we know what goals the product should achieve and how to do that.',
  Individual: 'Individual approach and custom development',
  OwnProduction: 'Own production, R&D unit, and technical team allow us to work with any task. We can create interactive courses or quests on all the LMSs using any learning technology.',
  Process: 'Process development and own LMS',
  HaveOwnPlatform: 'We have our own platform for hosting courses. This allows us to choose the optimal format for each project, analyze statistics, and quickly add unique features.',
  OurProducts: 'Our products',
  generalPublic: 'For the general public',
  ForBusinesses: 'For businesses',
  Massive: 'Massive open online courses',
  AnyTargetAudience: 'Any target audience and topic, certification, and evaluation',
  EducationalGames: 'Educational games',
  ArticulateStoryline: 'Articulate storyline and custom code',
  LearningPlatforms: 'Learning platforms',
  DevelopmentPlatform: 'Development of a platform, algorithms, and content',
  Cases: 'Cases',
  Onboarding: 'Onboarding and offboarding',
  Content: 'Content and technical implementation',
  EducationalEcosystem: 'Educational ecosystem',
  IndividualResearch: 'Individual research, educational algorithms, and content',
  OnlineCourses: 'Online courses',
  AnyTopic: 'Any topic and format',
  Nus: 'The New Ukrainian School (NUS)',
  teachTeachers: 'Task. The task was to teach teachers to learn online. We needed to develop Ukraineʼs first mandatory online course for all primary school teachers as part of the NUS reform.',
  DevelopedSimpleInformative: 'Solution. We developed a simple and informative course for teacher training. We have proven that nationwide online education is possible in Ukraine.',
  teachersHaveBeenTaught: 'Result. 265,000 teachers have been taught to learn online. 168,000 of them received a certificate for successful completion of the course.',
  IREx: 'IREX',
  promoteMediaLiteracy: 'Task. Our task was to promote media literacy in Ukraine and provide Ukrainians with tools for critical thinking and effective information analysis.',
  developedCreativeOnlineCourse: 'Solution. We developed a creative online course with animated materials, chatbots, tests, and modern visual identity. The course is available in three languages.',
  usersIREX: '42 000 users',
  NABu: 'NABU',
  developEducationalGame: 'Task. We had to develop an educational game in the format of case studies and interactive investigations for current and future NABU detectives.',
  developedAnEducationalGame: 'Solution. We developed an educational game containing 9 stages, video explanations, video cases of interrogation, search, and court hearing. We applied the edutainment approach and hosted the game on Articulate Storyline.',
  usersInFirstDay: '902 users in the first day, 12 866 users in half a year.',
  Feedback: 'Feedback',
  Victoria: 'Victoria Ivashinyuta',
  VictoriaDescript: 'Head of the NABU Open Office',
  InvestigationIsConducted: '"Investigation is conducted by NABU" has become the first online educational project for NABU, and the interactive format of the course was new for EdEra. Nevertheless, we coped well with this difficult and interesting task. Creativity, dedication, and coordinated teamwork were the key to our mutual success. And quarantine in the country failed to disturb our plans.',
  Prosvita: 'CEC: Prosvita',
  creativeConcept: 'Task. Development of a creative concept and an immersive educational platform about elections for every citizen of Ukraine.',
  educationalPlatformWhichOffersLearning: 'Solution. A gamified educational platform, which offers learning in the format of online communication, and a series of videos integrated into dialogues.',
  ResultPROSVITA: 'Result. An easy to navigate educational platform in the updated visual style of the CEC. The first modern educational platform in Ukraine on the basis of a state body.',
  Vladislav: 'Vladislav Yelenchin',
  ProductManager: 'Product Manager of the Council of Europe',
  EdEraFaced: '“EdEra faced an ambitious task — to customize its platform in 4 months and release 98 videos for 4 courses. And they succeeded! Most importantly, a high-quality product was created.”',
  Backstage: 'Backstage',
  BackstageTask: 'Task. Our task was to shift offline learning to an online format. We had to preserve the corporate ecosystem and create onboarding for new employees.',
  BackstageSolution: 'Solution. Full onboarding of a new employee — from corporate culture to accurate scripts and work protocols. Dozens of milestone tests and the final rating score of an employee.',
  BackstageResult: 'Result. Hundreds of employees underwent online onboarding and training, while salon directors evaluated their skills and made the final decision whether to include them in the team.',
  Karina: 'Karina Dubinina',
  KarinaDescript: 'founder of the Backstage beauty salons',
  KarinaFeedback: 'New employees join us all the time, so training is an urgent need. Together with the EdEra team, we have found a solution by creating a platform with online courses for employees. Now, the onboarding is automated. Employees have round-the-clock access to training materials and can take automated tests, making it easier for administrations to track the effectiveness of the process. Three courses for employees ensure regular training in an accessible language. Video tutorials reproduce the whole process of one’s work in an interesting format. The listener seems to be "present" directly in the workspace, and the platform itself is convenient and flexible.',
  Ukrtelecom: 'Ukrtelecom',
  UkrtelecomTask: 'Task. We had to create two training courses for Ukrtelecom employees: on digital literacy and business Ukrainian.',
  UkrtelecomSolution: 'Solution. We made corporate training dynamic and useful for hundreds of employees with different levels of skills and experience.',
  UkrtelecomResult: 'Result. We developed 2 ecosystems of corporate courses with video explanations, case studies, additional materials, and testing. Both courses are open to all Ukrtelecom employees.',
  Olesya: 'Olesya Pitsyk',
  OlesyaDescript: 'T&D specialist',
  OlesyaFeedback: 'Now, the training modules are available to all employees of our company on the corporate distance learning platform. Due to a wide target audience (both beginners and advanced users take those courses), we needed to find a partner who would make the training interesting and full of useful and relevant information for the business environment. Thanks to the coordinated work of methodologists, authors, and the production team, we have a quality product that we are satisfied with.',
  ProductCreation: 'Product creation process',
  ProductDevelopmentInvolves: 'Product development involves 7 steps from research to data analysis. We can develop a comprehensive product or, for example, only conduct market analysis and develop the framework of your project.',
  research: 'Market and audience research',
  teamAnalyzes: 'The R&D team analyzes the needs of the audience and the market.',
  EducationalMethodology: 'Educational methodology and R&D content',
  TeamDevelops: 'The team develops an educational framework: the structure and optimal methodology of the product and the content itself.',
  CommunicationPromotion: 'Communication and promotion',
  CreativeCommunication: 'Creative communication team develops and implements a product communication campaign: media partnerships, social networks, e-mail newsletters, etc.',
  ProjectConcept: 'Project concept and visual identity',
  designEachComponent: 'The creative team develops the project concept — its main messages and unique features. Then, we design each component of the product.',
  Production: 'Production',
  teamEnsures: 'The project team ensures content and technical production. Content production covers video, audio, and tests — from test shooting to the final post-production stage. Technical production is the development, design, and layout of the website.',
  ProductLaunch: 'Product launch and support',
  projectTeamLaunches: 'The project team launches the product and ensures technical and information support of users.',
  DataAnalysis: 'Data analysis',
  teamAnalyzesQuantitative: 'The R&D team analyzes quantitative and qualitative course data and user feedback.',
  question1: 'I have a finished course. Can I place it on your platform?',
  answer1: 'On the EdEra platform, we place only those educational products that are developed in partnership with us. However, if you are only looking for a platform to host your finished course, you can contact our partner Workademy',
  question2: 'Who can access your products?',
  answer2: 'All users of the EdEra platform will have access to courses for the general public. In case of corporate courses, only your target audience will see them. Such a course may be closed.',
  question3: 'Can I use my own design?',
  answer3: 'Yes, you can! If you have your own branding and guidelines for it, we will adapt the design to the online product format and create visual identity based on your brand book.',
  question4: 'Can you just shoot a course without promotion and placement?',
  answer4: 'Yes, we can make a turnkey course and pass all the materials for placement to you.',
  question5: 'What communication support do you offer?',
  answer5: 'We develop and implement full-fledged communication strategies and campaigns: from product promotion on social networks to special projects and collaborations with the media.',
  question6: 'Can users get certificates?',
  answer6: 'Yes, the generation of certificates is provided by all LMSs (learning management systems) platforms on which we place online products.',
  calculatePrice: 'We calculate the price of each project individually after a detailed brief. Email us at <a href="partnerships@ed-era.com">partnerships@ed-era.com</a>, and we will answer all your questions.',
  Share: 'Share on social networks',
  TellUs: 'Tell us your project idea and our partnership managers will contact you.',
  name: 'Your name',
  Company: 'Company name',
  Phone: 'Phone',
  Submit: 'Submit',
  WhatProblem: 'What problem would you like to solve together with us?',
};

changeLagnuage();

function changeLagnuage() {
  let language = lang.checked ? ua : eng;
  document.querySelectorAll('[text]').forEach(el => {
    el.innerHTML = language[el.getAttribute('text')];
  })
}
