name: workflow

on:
  push:
    branches: [ 'master', 'preproduction' ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: "eu-west-1"

    steps:
      - uses: actions/checkout@v2
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
      - name: cache
        uses: actions/cache@v2.1.3
        with:
          path: |
            **/node_modules
            **/node
          key: ${{ steps.extract_branch.outputs.branch }}
          restore-keys: ${{ steps.extract_branch.outputs.branch }}
      - name: AWS CLI
        uses: chrislennon/action-aws-cli@v1.1
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: true
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1
      - uses: actions/setup-node@v2
        with:
          node-version: '8.6.x'
      - run: |
          export BRANCH=${GITHUB_REF#refs/*/}

          ./build.sh $BRANCH
          ./deploy-aws.sh $BRANCH
